import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  "docs": [
    {
      "type": "doc",
      "id": "index",
      "label": "Overview"
    },
    {
      "type": "category",
      "label": "Vocabulary",
      "link": {
        "type": "doc",
        "id": "vocabularies/index"
      },
      "items": [
        {
          "type": "autogenerated",
          "dirName": "vocabularies"
        }
      ]
    },
    {
      "type": "category",
      "label": "Documentation",
      "items": [
        {
          "type": "doc",
          "id": "introduction"
        },
        {
          "type": "doc",
          "id": "examples"
        },
        {
          "type": "doc",
          "id": "about"
        }
      ]
    }
  ]
};

export default sidebars;
