version: 2
updates:
  # Enable version updates for pnpm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 10
    groups:
      nx:
        patterns:
          - "@nx/*"
          - "nx"
          - "nx-cloud"
      docusaurus:
        patterns:
          - "@docusaurus/*"
      mui:
        patterns:
          - "@mui/*"
          - "@emotion/*"
      testing:
        patterns:
          - "*test*"
          - "*vitest*"
          - "*playwright*"
          - "*jest*"
    ignore:
      # Don't update major versions automatically
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    commit-message:
      prefix: "chore"
      include: "scope"

  # Enable security updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"