# Cerbos Hub configuration for IFLA Standards
# This connects the repository to Cerbos Hub for GitOps policy management
---
apiVersion: api.cerbos.cloud/v1
labels:
  development:    # 'development' label pointing to the HEAD of the dev branch
    branch: dev
  preview:        # 'preview' label pointing to the HEAD of the dev branch (for preview environments)
    branch: dev
  production:     # 'production' label pointing to the HEAD of the main branch
    branch: main