# Cerbos Hub configuration for IFLA Standards
# This connects the repository to Cerbos Hub for GitOps policy management
---
apiVersion: api.cerbos.cloud/v1
git:
  git:
  workDir: cerbos
labels:
  latest:         # 'latest' label pointing to the HEAD of the main branch
    branch: main
  development:    # 'development' label pointing to the HEAD of the dev branch
    branch: dev
  stable:         # 'stable' label pointing to latest stable release
    branch: main