packages:
  - packages/*
  - standards/*
  - portal
  - tools/*
  - libs/*
  - apps/*

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - core-js
  - core-js-pure
  - esbuild
  - nx
  - puppeteer
  - sharp
