import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Main documentation sidebar for ISBD with multi-element set support
  docs: [
    {
      type: 'doc',
      id: 'index',
      label: 'ISBD Overview'
    },
    {
      type: 'category',
      label: 'Element Sets',
      link: {
        type: 'doc',
        id: 'elements/index'
      },
      items: [
        {
          type: 'category',
          label: 'ISBD Elements',
          link: {
            type: 'doc',
            id: 'elements/isbd/index'
          },
          items: [
            {
              type: 'category',
              label: 'Area 0',
              link: { type: 'doc', id: 'elements/isbd/area0/index' },
              items: [{ type: 'autogenerated', dirName: 'elements/isbd/area0' }]
            },
            {
              type: 'category',
              label: 'Area 1',
              link: { type: 'doc', id: 'elements/isbd/area1/index' },
              items: [{ type: 'autogenerated', dirName: 'elements/isbd/area1' }]
            },
            {
              type: 'category',
              label: 'Area 2',
              link: { type: 'doc', id: 'elements/isbd/area2/index' },
              items: [{ type: 'autogenerated', dirName: 'elements/isbd/area2' }]
            },
            {
              type: 'category',
              label: 'Area 3',
              link: { type: 'doc', id: 'elements/isbd/area3/index' },
              items: [{ type: 'autogenerated', dirName: 'elements/isbd/area3' }]
            },
            {
              type: 'category',
              label: 'Area 4',
              link: { type: 'doc', id: 'elements/isbd/area4/index' },
              items: [{ type: 'autogenerated', dirName: 'elements/isbd/area4' }]
            },
            {
              type: 'category',
              label: 'Area 5',
              link: { type: 'doc', id: 'elements/isbd/area5/index' },
              items: [{ type: 'autogenerated', dirName: 'elements/isbd/area5' }]
            },
            {
              type: 'category',
              label: 'Area 6',
              link: { type: 'doc', id: 'elements/isbd/area6/index' },
              items: [{ type: 'autogenerated', dirName: 'elements/isbd/area6' }]
            },
            {
              type: 'category',
              label: 'Area 7',
              link: { type: 'doc', id: 'elements/isbd/area7/index' },
              items: [{ type: 'autogenerated', dirName: 'elements/isbd/area7' }]
            },
            {
              type: 'category',
              label: 'Area 8',
              link: { type: 'doc', id: 'elements/isbd/area8/index' },
              items: [{ type: 'autogenerated', dirName: 'elements/isbd/area8' }]
            }
          ]
        },
        {
          type: 'category',
          label: 'ISBD Unconstrained',
          link: {
            type: 'doc',
            id: 'elements/unconstrained/index'
          },
          items: [
            {
              type: 'category',
              label: 'All Elements',
              link: { type: 'doc', id: 'elements/unconstrained/elements/index' },
              items: [{ type: 'autogenerated', dirName: 'elements/unconstrained/elements' }]
            }
          ]
        }
      ]
    },
    {
      type: 'category',
      label: 'Vocabularies',
      link: {
        type: 'doc',
        id: 'vocabularies/index'
      },
      items: [
        'vocabularies/contentform',
        'vocabularies/contentformbase',
        'vocabularies/mediatype',
        {
          type: 'category',
          label: 'Content Qualification',
          items: [
            'vocabularies/contentqualification/dimensionality',
            'vocabularies/contentqualification/motion',
            'vocabularies/contentqualification/sensoryspecification',
            'vocabularies/contentqualification/type'
          ]
        }
      ]
    },
    {
      type: 'category',
      label: 'Documentation',
      items: [
        {
          type: 'doc',
          id: 'introduction',
          label: 'Introduction'
        },
        {
          type: 'doc',
          id: 'assessment',
          label: 'Assessment Guidelines'
        },
        {
          type: 'doc',
          id: 'examples',
          label: 'Examples'
        },
        {
          type: 'doc',
          id: 'glossary',
          label: 'Glossary'
        },
        {
          type: 'doc',
          id: 'about',
          label: 'About ISBD'
        }
      ]
    }
  ],
};

export default sidebars;