#!/usr/bin/env tsx

/**
 * Code Generation Tool for OpenAPI → TypeScript Types
 *
 * This tool generates TypeScript types from OpenAPI specifications
 * and integrates them with our Zod schemas for runtime validation.
 *
 * Usage:
 *   pnpm tsx tools/codegen/generate-types.ts
 *   pnpm tsx tools/codegen/generate-types.ts --spec=path/to/spec.yaml
 */

import { promises as fs } from 'fs';
import { join } from 'path';

class TypesGenerator {
  constructor() {}

  async generate(): Promise<void> {
    console.log('🔧 IFLA Standards Platform - Type Generation');
    console.log('==========================================');

    try {
      // Phase 1: Discover OpenAPI specs
      const specs = await this.discoverSpecs();
      console.log(`📋 Found ${specs.length} OpenAPI specifications`);

      if (specs.length === 0) {
        console.log(
          'ℹ️  No OpenAPI specs found. This tool will generate types when specs are added.',
        );
        console.log('📁 Place OpenAPI specs in: packages/contracts/openapi/');
        return;
      }

      // Phase 2: Generate types for each spec
      for (const spec of specs) {
        await this.generateFromSpec(spec);
      }

      console.log('✅ Type generation completed successfully!');
    } catch (error) {
      console.error('❌ Type generation failed:', error);
      process.exit(1);
    }
  }

  private async discoverSpecs(): Promise<string[]> {
    const specsDir = join(process.cwd(), 'packages/contracts/openapi');

    try {
      const files = await fs.readdir(specsDir);
      return files
        .filter(
          (file) =>
            file.endsWith('.yaml') ||
            file.endsWith('.yml') ||
            file.endsWith('.json'),
        )
        .map((file) => join(specsDir, file));
    } catch (error) {
      // Directory doesn't exist yet - that's fine
      return [];
    }
  }

  private async generateFromSpec(specPath: string): Promise<void> {
    console.log(`🔄 Processing: ${specPath}`);

    const { exec } = await import('child_process');
    const { promisify } = await import('util');
    const { basename } = await import('path');
    const execAsync = promisify(exec);

    const outputDir = join(process.cwd(), 'packages/contracts/types/ts');
    await fs.mkdir(outputDir, { recursive: true });

    // Generate output filename based on input spec name
    const specName = basename(specPath).replace(/\.(yaml|yml|json)$/, '');
    const outputFile = join(outputDir, `${specName}.ts`);

    console.log(`📝 Generating types to: ${outputFile}`);

    try {
      // Use openapi-typescript to generate types
      const command = `npx openapi-typescript "${specPath}" -o "${outputFile}"`;
      await execAsync(command);

      // Add header comment to generated file
      const content = await fs.readFile(outputFile, 'utf-8');
      const header = `/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 * Source: ${basename(specPath)}
 * Generated: ${new Date().toISOString()}
 */

`;
      await fs.writeFile(outputFile, header + content);

      console.log(`✅ Types generated: ${outputFile}`);
    } catch (error) {
      console.error(`❌ Failed to generate types for ${specPath}:`, error);
      throw error;
    }
  }
}

// CLI handling
async function main() {
  const generator = new TypesGenerator();
  await generator.generate();
}

// Run if called directly
if (require.main === module) {
  main().catch(console.error);
}

export { TypesGenerator };
