export const mockNamespaceData = [
  {
    id: 'isbd',
    name: 'ISBD',
    description: 'International Standard Bibliographic Description',
    reviewGroup: 'isbd-review-group',
    visibility: 'public' as const,
    status: 'active' as const,
    conceptSchemes: 5,
    elementSets: 2,
    translations: ['en', 'fr', 'es', 'de', 'it'],
    lastModified: '2024-08-04T20:07:00.000Z',
    createdAt: '2023-01-01T00:00:00.000Z',
  },
  {
    id: 'FRBR',
    name: 'FRBR',
    description: 'Functional Requirements for Bibliographic Records',
    reviewGroup: 'frbr-review-group',
    visibility: 'public' as const,
    status: 'active' as const,
    conceptSchemes: 4,
    elementSets: 3,
    translations: ['en', 'fr', 'es'],
    lastModified: '2024-08-04T18:37:00.000Z',
    createdAt: '2022-06-15T00:00:00.000Z',
  },
  {
    id: 'ISBDM',
    name: 'ISBD(M)',
    description: 'International Standard Bibliographic Description for Monographic Publications',
    reviewGroup: 'isbd-review-group',
    visibility: 'public' as const,
    status: 'active' as const,
    conceptSchemes: 3,
    elementSets: 2,
    translations: ['en', 'fr'],
    lastModified: '2024-08-11T22:06:00.000Z',
    createdAt: '2023-03-20T00:00:00.000Z',
  },
  {
    id: 'LRM',
    name: 'LRM',
    description: 'Library Reference Model',
    reviewGroup: 'lrm-review-group',
    visibility: 'public' as const,
    status: 'active' as const,
    conceptSchemes: 6,
    elementSets: 3,
    translations: ['en', 'fr', 'es', 'de'],
    lastModified: '2024-08-04T18:37:00.000Z',
    createdAt: '2022-01-10T00:00:00.000Z',
  },
  {
    id: 'unimarc',
    name: 'UNIMARC',
    description: 'Universal Machine-Readable Cataloguing',
    reviewGroup: 'unimarc-review-group',
    visibility: 'public' as const,
    status: 'active' as const,
    conceptSchemes: 8,
    elementSets: 4,
    translations: ['en', 'fr', 'es', 'it', 'pt'],
    lastModified: '2024-08-04T18:37:00.000Z',
    createdAt: '2021-11-05T00:00:00.000Z',
  },
  {
    id: 'muldicat',
    name: 'MulDiCat',
    description: 'Multilingual Dictionary of Cataloguing Terms and Concepts',
    reviewGroup: 'muldicat-review-group',
    visibility: 'public' as const,
    status: 'active' as const,
    conceptSchemes: 10,
    elementSets: 1,
    translations: ['en', 'fr', 'es', 'de', 'it', 'pt', 'ru', 'ar', 'zh', 'ja'],
    lastModified: '2024-08-04T18:37:00.000Z',
    createdAt: '2022-09-12T00:00:00.000Z',
  },
  {
    id: 'test-integration',
    name: 'Test Integration',
    description: 'Test namespace for integration testing',
    reviewGroup: 'test-review-group',
    visibility: 'private' as const,
    status: 'inactive' as const,
    conceptSchemes: 0,
    elementSets: 1,
    translations: ['en'],
    lastModified: '2024-07-23T12:41:00.000Z',
    createdAt: '2024-07-23T12:41:00.000Z',
  },
  {
    id: 'newtest',
    name: 'New Test',
    description: 'New test namespace for development',
    reviewGroup: 'test-review-group',
    visibility: 'private' as const,
    status: 'archived' as const,
    conceptSchemes: 0,
    elementSets: 0,
    translations: ['en'],
    lastModified: '2024-08-04T18:37:00.000Z',
    createdAt: '2024-08-04T18:37:00.000Z',
  },
];