import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Main documentation sidebar
  docs: [
    'index',
    'modern-documentation-platform',
    {
      type: 'category',
      label: 'Author Guides',
      link: {
        type: 'generated-index',
        title: 'IFLA Standards Author Guides',
        description: 'Learn how to create and manage IFLA standards content',
        keywords: ['guides', 'authoring', 'components'],
      },
      items: [
        {
          type: 'category',
          label: 'Component Guides',
          link: {
            type: 'generated-index',
            title: 'Component Usage Guides',
            description: 'Learn how to use the components available in MDX files',
          },
          items: [
            'guides/components/vocabulary-table',
            'guides/components/element-reference',
            'guides/components/figure-component',
            'guides/components/example-table',
            'guides/components/mandatory-component',
            'guides/components/seealso-component',
            'guides/components/inlink-component',
            'guides/components/outlink-component',
          ],
        },
        {
          type: 'category',
          label: 'Authoring Guides',
          link: {
            type: 'generated-index',
            title: 'Content Creation Guides',
            description: 'Learn how to create vocabularies and write content',
          },
          items: [
            'guides/authoring/vocabulary-sme-guide',
            'guides/authoring/vocabulary-creation-technical',
            'guides/authoring/vocabulary-table-usage',
          ],
        },
        {
          type: 'category',
          label: 'Profiles & Examples',
          items: [{ type: 'autogenerated', dirName: 'guides/profiles' }],
        },
        {
          type: 'category',
          label: 'Vocabulary Examples',
          link: {
            type: 'generated-index',
            title: 'Vocabulary Examples',
            description: 'Real-world examples of vocabularies',
          },
          items: [
            'guides/examples/minimal-vocabulary',
            'guides/examples/skos-vocabulary-example',
            'guides/examples/sensory-specification-vocabulary',
            'guides/examples/sensory-test-vocabulary',
            'guides/examples/vocabulary-table-csv-simple',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Tutorials',
      items: [{ type: 'autogenerated', dirName: 'tutorial-basics' }],
    },
    {
      type: 'category',
      label: 'Advanced',
      items: [{ type: 'autogenerated', dirName: 'tutorial-extras' }],
    },
  ],
};

export default sidebars;
