name: build-preview
on: [push, pull_request]
permissions: {contents: write}
jobs:
  site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - run: pnpm install --frozen-lockfile
      - name: Build all docs
        run: BASE_URL="/standards-dev/" pnpm -r build
      - name: Deploy to gh-pages
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build
