name: Test Site Builds

on:
  # Disabled - legacy workflow superseded by nx-optimized-ci.yml
  # push:
  #   branches: [main, dev]
    paths:
      - 'packages/**'
      - 'standards/**'
      - 'portal/**'
      - 'scripts/**'
      - '.github/workflows/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'tsconfig.json'
  pull_request:
    branches: [main, dev]
  workflow_dispatch:
    inputs:
      site:
        description: 'Site to test (specific site or "all")'
        required: false
        default: 'all'
      environment:
        description: 'Environment to test'
        required: false
        default: 'production'
        type: choice
        options:
          - localhost
          - preview
          - production

jobs:
  test-unit-and-types:
    name: Unit Tests & Type Safety
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build theme package
        run: pnpm --filter @ifla/theme build

      - name: TypeScript type checking
        run: pnpm typecheck

      - name: ESLint code quality
        run: pnpm lint --quiet

      - name: Unit and integration tests
        run: pnpm test

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: coverage/

  test-configurations:
    name: Test Site Configurations
    runs-on: ubuntu-latest
    needs: test-unit-and-types
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build theme package
        run: pnpm --filter @ifla/theme build

      - name: Test site configurations
        run: |
          SITE=${{ github.event.inputs.site || 'all' }}
          ENV=${{ github.event.inputs.environment || (github.ref_name == 'main' && 'production' || github.ref_name == 'dev' && 'development' || 'production') }}
          node scripts/test-site-builds.js --site $SITE --env $ENV --skip-build

  test-site-builds:
    name: Test Site Builds
    runs-on: ubuntu-latest
    needs: test-configurations
    strategy:
      matrix:
        site: [portal, ISBDM, LRM, FRBR, isbd, muldicat, unimarc]
      fail-fast: false
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build theme package
        run: pnpm --filter @ifla/theme build

      - name: Test ${{ matrix.site }} build
        run: |
          ENV=${{ github.event.inputs.environment || (github.ref_name == 'main' && 'production' || github.ref_name == 'dev' && 'development' || 'production') }}
          node scripts/test-site-builds.js --site ${{ matrix.site }} --env $ENV
        env:
          NODE_OPTIONS: --max-old-space-size=8192

      - name: Upload build artifacts on success
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.site }}
          path: |
            ${{ matrix.site == 'portal' && 'portal' || format('standards/{0}', matrix.site) }}

      - name: Upload build artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: failed-build-${{ matrix.site }}
          path: |
            ${{ matrix.site == 'portal' && 'portal' || format('standards/{0}', matrix.site) }}/build/
            ${{ matrix.site == 'portal' && 'portal' || format('standards/{0}', matrix.site) }}/logs/


  summary:
    name: Test Summary
    runs-on: ubuntu-latest
    needs: [test-unit-and-types, test-configurations, test-site-builds]
    if: always()
    
    steps:
      - name: Check test results
        run: |
          echo "## Regression Test Summary"
          echo ""
          echo "### Unit Tests & Type Safety"
          if [ "${{ needs.test-unit-and-types.result }}" == "success" ]; then
            echo "✅ All unit tests and type checking passed"
          else
            echo "❌ Unit tests or type checking failed"
          fi
          echo ""
          echo "### Configuration Tests"
          if [ "${{ needs.test-configurations.result }}" == "success" ]; then
            echo "✅ All site configurations passed"
          else
            echo "❌ Site configuration tests failed"
          fi
          echo ""
          echo "### Build Tests"
          if [ "${{ needs.test-site-builds.result }}" == "success" ]; then
            echo "✅ All sites built successfully"
          else
            echo "❌ Some site builds failed"
          fi
      - name: Set job status
        if: |
          needs.test-unit-and-types.result != 'success' ||
          needs.test-configurations.result != 'success' ||
          needs.test-site-builds.result != 'success'
        run: exit 1
